#!/bin/bash
set -euo pipefail

WALLET="0xd69f9856a569b1655b43b0395b7c2923a217cfe0"
echo "=== Obtener gas para Base MEV Bot ==="
echo "Wallet: $WALLET"
echo "Necesitas: 0.003 ETH (~$6) para 1000 transacciones"
echo ""
echo "OPCIONES GRATIS:"
echo ""
echo "1) BRIDGE DESDE OTRA CHAIN (si tienes dust en cualquier chain):"
echo "   - Orbiter Finance: https://www.orbiter.finance/?source=Ethereum&dest=Base"
echo "   - Min bridge: 0.005 ETH desde Ethereum/Arbitrum/Optimism"
echo "   - Relay.link: https://relay.link/bridge/base (min $1)"
echo ""
echo "2) FAUCETS BASE (cantidades tiny pero gratis):"
echo "   - Coinbase Wallet: la app te regala gas al activar Base"
echo "   - Thirdweb: https://thirdweb.com/base (requiere account)"
echo ""
echo "3) CEX WITHDRAW (más rápido):"
echo "   - Coinbase: withdraw 0.005 ETH a Base directamente (gratis)"
echo "   - Binance: withdraw ETH via Base network"
echo ""
echo "4) EARN (sin capital):"
echo "   - Coinbase Learning Rewards → withdraw a Base"
echo "   - Guild.xyz quests en Base (airdrops de ETH)"
echo ""
echo "5) PEDIR PRESTADO (comunidad):"
echo "   - r/ethdev — alguien puede enviar 0.001 ETH dust"
echo "   - Discord Base — canal de faucets"
echo ""
echo "Una vez tengas ETH en la wallet, ejecuta:"
echo "  ./deploy.sh   # deplegar contrato"
echo "  # quitar --dry-run del bot"
echo ""
echo "El bot se auto-financia después:"
echo "  Profit del arb queda en contrato → withdraw cada 50 cycles → paga gas del siguiente trade"
